/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseprojet;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author El Mysto
 */
public class Enseignant extends javax.swing.JFrame {
Connection cn = JavaConnectDb.ConnecrDb();
    /**
     * Creates new form Enseignant
     */
    public Enseignant() {
        initComponents();
        
        inser_button.setEnabled(false);
        supp_button.setEnabled(false);
         mat_pane.setVisible(false);
        nom_pane.setVisible(false);
        prenom_pane.setVisible(false);
         inser_pane.setVisible(false);
         supp_pane.setVisible(false);
         exist_pane.setVisible(false);
         change_pane.setVisible(false);
        refresh();
        
    }
    public  void refresh(){
             try{
            Connection cn = JavaConnectDb.ConnecrDb();
           //   Statement myStmt2 = cn.createStatement();
             //  myStmt2.executeQuery("Alter Session set NLS_DATE_FORMAT = 'DD/MM/YYYY'");
            PreparedStatement ps=cn.prepareStatement("select * from enseignant");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)table1.getModel();
            tm.setRowCount(0);
            while(rs.next()){
      Object o[]={rs.getInt("matricule_ens"),rs.getString("nom_ens"),rs.getString("prenom_ens")};
      tm.addRow(o);
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        exist_pane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        mat_pane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricule = new javax.swing.JTextField();
        prenom_pane = new javax.swing.JPanel();
        prenom = new javax.swing.JTextField();
        aaa = new javax.swing.JLabel();
        nom_pane = new javax.swing.JPanel();
        nom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inser_rad = new javax.swing.JRadioButton();
        supp_rad = new javax.swing.JRadioButton();
        inser_pane = new javax.swing.JPanel();
        inser_button = new javax.swing.JButton();
        supp_pane = new javax.swing.JPanel();
        supp_button = new javax.swing.JButton();
        change_rad = new javax.swing.JRadioButton();
        change_pane = new javax.swing.JPanel();
        change_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Ce nom existe plus d'une fois , svp entrer ça matricule.");

        javax.swing.GroupLayout exist_paneLayout = new javax.swing.GroupLayout(exist_pane);
        exist_pane.setLayout(exist_paneLayout);
        exist_paneLayout.setHorizontalGroup(
            exist_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exist_paneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        exist_paneLayout.setVerticalGroup(
            exist_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exist_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        table1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Matricule", "Nom", "Prénom"
            }
        ));
        jScrollPane2.setViewportView(table1);

        jLabel1.setText("Matricule");

        matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculeActionPerformed(evt);
            }
        });
        matricule.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matriculeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                matriculeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                matriculeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout mat_paneLayout = new javax.swing.GroupLayout(mat_pane);
        mat_pane.setLayout(mat_paneLayout);
        mat_paneLayout.setHorizontalGroup(
            mat_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mat_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mat_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mat_paneLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)))
                .addContainerGap())
        );
        mat_paneLayout.setVerticalGroup(
            mat_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mat_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prenomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prenomKeyTyped(evt);
            }
        });

        aaa.setText("Prenom");

        javax.swing.GroupLayout prenom_paneLayout = new javax.swing.GroupLayout(prenom_pane);
        prenom_pane.setLayout(prenom_paneLayout);
        prenom_paneLayout.setHorizontalGroup(
            prenom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prenom_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prenom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prenom_paneLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(aaa))
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prenom_paneLayout.setVerticalGroup(
            prenom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prenom_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aaa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nom_pane.setPreferredSize(new java.awt.Dimension(140, 62));

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomKeyTyped(evt);
            }
        });

        jLabel2.setText("Nom");

        javax.swing.GroupLayout nom_paneLayout = new javax.swing.GroupLayout(nom_pane);
        nom_pane.setLayout(nom_paneLayout);
        nom_paneLayout.setHorizontalGroup(
            nom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nom_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(nom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nom_paneLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)))
                .addGap(146, 146, 146))
        );
        nom_paneLayout.setVerticalGroup(
            nom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nom_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(inser_rad);
        inser_rad.setText("Insertion");
        inser_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inser_radActionPerformed(evt);
            }
        });

        bg.add(supp_rad);
        supp_rad.setText("Suppression");
        supp_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_radActionPerformed(evt);
            }
        });

        inser_button.setText("insert ↑");
        inser_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inser_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inser_paneLayout = new javax.swing.GroupLayout(inser_pane);
        inser_pane.setLayout(inser_paneLayout);
        inser_paneLayout.setHorizontalGroup(
            inser_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inser_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inser_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inser_paneLayout.setVerticalGroup(
            inser_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inser_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inser_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        supp_button.setText("Supprimer ❌");
        supp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_buttonActionPerformed(evt);
            }
        });
        supp_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supp_buttonKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout supp_paneLayout = new javax.swing.GroupLayout(supp_pane);
        supp_pane.setLayout(supp_paneLayout);
        supp_paneLayout.setHorizontalGroup(
            supp_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supp_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supp_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        supp_paneLayout.setVerticalGroup(
            supp_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supp_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supp_button)
                .addContainerGap())
        );

        bg.add(change_rad);
        change_rad.setText("Changement");
        change_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_radActionPerformed(evt);
            }
        });

        change_pane.setPreferredSize(new java.awt.Dimension(89, 45));

        change_button.setText("Changer");
        change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout change_paneLayout = new javax.swing.GroupLayout(change_pane);
        change_pane.setLayout(change_paneLayout);
        change_paneLayout.setHorizontalGroup(
            change_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, change_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(change_button)
                .addContainerGap())
        );
        change_paneLayout.setVerticalGroup(
            change_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(change_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(change_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inser_rad)
                        .addGap(48, 48, 48)
                        .addComponent(supp_rad)
                        .addGap(48, 48, 48)
                        .addComponent(change_rad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(mat_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nom_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prenom_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(change_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(supp_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(exist_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inser_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supp_rad)
                    .addComponent(inser_rad)
                    .addComponent(change_rad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nom_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mat_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(prenom_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supp_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inser_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exist_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyReleased
        // TODO add your handling code here:
        if((nom.getText().equals(""))||(matricule.getText().equals(""))||(prenom.getText().equals(""))){
            if(inser_rad.isSelected()){
                 inser_button.setEnabled(false);
            }
     
                if(change_rad.isSelected()){
                    change_button.setEnabled(false);
                }
            
            
            if(supp_rad.isSelected()){
                    supp_button.setEnabled(false);
                    }
        }
        

       
    }//GEN-LAST:event_nomKeyReleased

    private void nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_nomKeyTyped

    private void prenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomKeyReleased
        // TODO add your handling code here:
        
            if(inser_rad.isSelected()){
                if((nom.getText().equals(""))||(matricule.getText().equals(""))||(prenom.getText().equals(""))){
                 inser_button.setEnabled(false);}else{
                    inser_button.setEnabled(true);
                }
                
            }
     
                if(change_rad.isSelected()){
                    if((nom.getText().equals(""))||(matricule.getText().equals(""))||(prenom.getText().equals(""))){
                    change_button.setEnabled(false);}
                    else{
                    change_button.setEnabled(true);
                    }
                }
            
            
            if(supp_rad.isSelected()){
                if((nom.getText().equals(""))||(matricule.getText().equals(""))||(prenom.getText().equals(""))){
                    supp_button.setEnabled(false);}else{
                    supp_button.setEnabled(true);
                    
                }
                }
                    
        

    }//GEN-LAST:event_prenomKeyReleased

    private void prenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_prenomKeyTyped

    private void inser_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inser_radActionPerformed
        // TODO add your handling code here:
        mat_pane.setVisible(true);
        nom_pane.setVisible(true);
        change_pane.setVisible(false);
        prenom_pane.setVisible(true);
        supp_pane.setVisible(false);
        inser_pane.setVisible(true);
        nom.setText("");
        prenom.setText("");
        matricule.setText("");
     

    }//GEN-LAST:event_inser_radActionPerformed

    private void supp_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_radActionPerformed
        // TODO add your handling code here:
        nom.setText("");
        change_pane.setVisible(false);
        prenom.setText("");
  
        matricule.setText("");
        mat_pane.setVisible(true);
        nom_pane.setVisible(true);
   
        prenom_pane.setVisible(false);
        

        inser_pane.setVisible(false);
        supp_pane.setVisible(true);

    }//GEN-LAST:event_supp_radActionPerformed

    private void inser_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inser_buttonActionPerformed
        // TODO add your handling code here:
        try {
            
            String sql ="insert into enseignant(matricule_ens,nom_ens,prenom_ens) values (?,?,?)";
            PreparedStatement ps=cn.prepareStatement(sql);
            ps.setInt(1,Integer.parseInt(matricule.getText()));
            ps.setString(2,nom.getText());
            ps.setString(3,prenom.getText());
            
            ps.executeUpdate();
            refresh();
            JOptionPane.showMessageDialog(this,"saved successfully");
            nom.setText("");
            prenom.setText("");
            matricule.setText("");

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_inser_buttonActionPerformed

    private void supp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = JavaConnectDb.ConnecrDb();
            PreparedStatement st = cn.prepareStatement("DELETE FROM enseignant WHERE nom_ens = ? and matricule_ens=?");
            Statement myStmt = cn.createStatement();
            ResultSet myRs = myStmt.executeQuery("select * from enseignant");
            st.setString(1,nom.getText());
            st.setString(2,matricule.getText());
            if (matricule.getText().equals("")){
                PreparedStatement st1 = cn.prepareStatement("DELETE FROM enseignant WHERE nom_ens = ?");
                st1.setString(1,nom.getText());
                int i=0;
                while(myRs.next()) {
                    if(nom.getText().equals(myRs.getString("nom_ens"))){
                        i++;}
                }
                if (i>1){
                    exist_pane.setVisible(true);
                }else{
                    st1.executeUpdate();

                    nom.setText("");
                    supp_button.setEnabled(false);
                    if (i == 0){
                        JOptionPane.showMessageDialog(this,"Le nom n'existe pas ! ");
                    }else{
                        JOptionPane.showMessageDialog(this,"deleted successfully");
                    }
                }
            }else{

                exist_pane.setVisible(false);
                PreparedStatement st2 = cn.prepareStatement("DELETE FROM enseignant WHERE nom_ens = ? and matricule_ens=?");

                st2.setString(1,nom.getText());
                st2.setString(2,matricule.getText());
                st2.executeUpdate();
                JOptionPane.showMessageDialog(this,"deleted successfully");
                matricule.setText("");
                nom.setText("");
            }
            refresh();

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }

    }//GEN-LAST:event_supp_buttonActionPerformed

    private void supp_buttonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supp_buttonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supp_buttonKeyReleased

    private void matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculeActionPerformed

    private void matriculeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculeKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_matriculeKeyPressed

    private void matriculeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculeKeyReleased
        // TODO add your handling code here:
        if((nom.getText().equals(""))||(matricule.getText().equals(""))||(prenom.getText().equals(""))){
            if(inser_rad.isSelected()){
                 inser_button.setEnabled(false);
            }
     
                if(change_rad.isSelected()){
                    change_button.setEnabled(false);
                }
            
            
            if(supp_rad.isSelected()){
                    supp_button.setEnabled(false);
                    }
        }
        try{
            Connection cn = JavaConnectDb.ConnecrDb();
            Statement myStmt3 = cn.createStatement();
            ResultSet myRs3 = myStmt3.executeQuery("select * from enseignant where matricule_ens = "+matricule.getText());
            if(myRs3.next()) {
                nom.setText(myRs3.getString("nom_ens"));
                supp_button.setEnabled(true);
            }else{
                supp_button.setEnabled(false);
                nom.setText("");
            }

        }catch(Exception e){

        }
        /********** change button ************/
         try{ 
           
        if(change_rad.isSelected()){
            
            Connection cn = JavaConnectDb.ConnecrDb();
            PreparedStatement st50 = cn.prepareStatement("SELECT *  FROM enseignant WHERE matricule_ens = ? ");
            st50.setInt(1,Integer.parseInt(matricule.getText()));
            ResultSet myRs50 = st50.executeQuery();
            if(myRs50.next()) {
                
                nom_pane.setVisible(true);  
                prenom_pane.setVisible(true); 
                nom.setText(myRs50.getString("nom_ens"));
                prenom.setText(myRs50.getString("prenom_ens"));
                
                
                change_button.setEnabled(true);
            }else{
              nom_pane.setVisible(false);  
                prenom_pane.setVisible(false); 
                 
                change_button.setEnabled(false);
                nom.setText("");
                prenom.setText("");
                
            }
              
          }

        }catch(Exception e){
         
        }
    }//GEN-LAST:event_matriculeKeyReleased

    private void matriculeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculeKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_matriculeKeyTyped

    private void change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = JavaConnectDb.ConnecrDb();

            PreparedStatement st = cn.prepareStatement("UPDATE enseignant Set nom_ens = ? , prenom_ens = ? where matricule_ens = ?");
            st.setString(1,nom.getText());
            st.setString(2,prenom.getText());
            
            st.setString(3,matricule.getText());

           
            st.executeUpdate();
            refresh();
            nom.setText("");
            prenom.setText("");
            
            //matricule.setText("");
           
            JOptionPane.showMessageDialog(this,"changé avec succès");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_change_buttonActionPerformed

    private void change_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_radActionPerformed
        // TODO add your handling code here:
        nom.setText("");
        change_button.setEnabled(false);
        prenom.setText("");
  
        matricule.setText("");
        mat_pane.setVisible(true);
        nom_pane.setVisible(false);
   
        prenom_pane.setVisible(false);
        

        inser_pane.setVisible(false);
        supp_pane.setVisible(false);
        change_pane.setVisible(true);
    }//GEN-LAST:event_change_radActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enseignant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aaa;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton change_button;
    private javax.swing.JPanel change_pane;
    private javax.swing.JRadioButton change_rad;
    private javax.swing.JPanel exist_pane;
    private javax.swing.JButton inser_button;
    private javax.swing.JPanel inser_pane;
    private javax.swing.JRadioButton inser_rad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mat_pane;
    private javax.swing.JTextField matricule;
    private javax.swing.JTextField nom;
    private javax.swing.JPanel nom_pane;
    private javax.swing.JTextField prenom;
    private javax.swing.JPanel prenom_pane;
    private javax.swing.JButton supp_button;
    private javax.swing.JPanel supp_pane;
    private javax.swing.JRadioButton supp_rad;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
