/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseprojet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author El Mysto
 */
public class EtudiantUnite extends javax.swing.JFrame {
    Connection cn = JavaConnectDb.ConnecrDb();

    /**
     * Creates new form EtudiantUnite
     */
    public EtudiantUnite() {
        initComponents();
       
        inser_button.setEnabled(false);
        change_button.setEnabled(false);
        supp_button.setEnabled(false);
        change_pane.setVisible(false);
          inser_pane.setVisible(false);
        supp_pane.setVisible(false);
         mat_pane.setVisible(false);
        nom_pane.setVisible(false);
        code_pane.setVisible(false);
        cc_pane.setVisible(false);
        tp_pane.setVisible(false);
        modulename_pane.setVisible(false);
        examen_pane.setVisible(false);
         exist_pane.setVisible(false);
      
        refresh();
        
    }
    public void refresh(){
             try{
            Connection cn = JavaConnectDb.ConnecrDb();
           //   Statement myStmt2 = cn.createStatement();
             //  myStmt2.executeQuery("Alter Session set NLS_DATE_FORMAT = 'DD/MM/YYYY'");
            PreparedStatement ps=cn.prepareStatement("select * from etudiantunite");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)table1.getModel();
            tm.setRowCount(0);
            while(rs.next()){
      Object o[]={rs.getInt("Matricule_etu"),rs.getString("code_unite"),rs.getString("note_cc"),rs.getString("note_tp"),rs.getString("note_examen")};
      tm.addRow(o);
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        exist_pane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        code_pane = new javax.swing.JPanel();
        codeUNITE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cc_pane = new javax.swing.JPanel();
        noteCC = new javax.swing.JTextField();
        aaa = new javax.swing.JLabel();
        tp_pane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        noteTP = new javax.swing.JTextField();
        examen_pane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        noteEX = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        inser_pane = new javax.swing.JPanel();
        inser_button = new javax.swing.JButton();
        supp_pane = new javax.swing.JPanel();
        supp_button = new javax.swing.JButton();
        mat_pane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricule = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        nom_pane = new javax.swing.JPanel();
        nom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        change_pane = new javax.swing.JPanel();
        change_button = new javax.swing.JButton();
        modulename_pane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Ce nom existe plus d'une fois , svp entrer ça matricule.");

        javax.swing.GroupLayout exist_paneLayout = new javax.swing.GroupLayout(exist_pane);
        exist_pane.setLayout(exist_paneLayout);
        exist_paneLayout.setHorizontalGroup(
            exist_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exist_paneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        exist_paneLayout.setVerticalGroup(
            exist_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exist_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        table1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matricule", "Code Unite", "Note CC", "Note TP", "Note Examen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table1);

        codeUNITE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeUNITEActionPerformed(evt);
            }
        });
        codeUNITE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeUNITEKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codeUNITEKeyTyped(evt);
            }
        });

        jLabel2.setText("Code Unite");

        noteCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noteCCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noteCCKeyTyped(evt);
            }
        });

        aaa.setText("Note CC");

        jLabel4.setText("Note TP");

        noteTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteTPActionPerformed(evt);
            }
        });
        noteTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noteTPKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noteTPKeyTyped(evt);
            }
        });

        examen_pane.setPreferredSize(new java.awt.Dimension(140, 62));

        jLabel5.setText("Note Examen");

        noteEX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noteEXKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout examen_paneLayout = new javax.swing.GroupLayout(examen_pane);
        examen_pane.setLayout(examen_paneLayout);
        examen_paneLayout.setHorizontalGroup(
            examen_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, examen_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noteEX, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(examen_paneLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        examen_paneLayout.setVerticalGroup(
            examen_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examen_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noteEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tp_paneLayout = new javax.swing.GroupLayout(tp_pane);
        tp_pane.setLayout(tp_paneLayout);
        tp_paneLayout.setHorizontalGroup(
            tp_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tp_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noteTP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tp_paneLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(48, 48, 48)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examen_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tp_paneLayout.setVerticalGroup(
            tp_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tp_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noteTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(examen_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout cc_paneLayout = new javax.swing.GroupLayout(cc_pane);
        cc_pane.setLayout(cc_paneLayout);
        cc_paneLayout.setHorizontalGroup(
            cc_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cc_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cc_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cc_paneLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(aaa))
                    .addComponent(noteCC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cc_paneLayout.setVerticalGroup(
            cc_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cc_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aaa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noteCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(tp_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout code_paneLayout = new javax.swing.GroupLayout(code_pane);
        code_pane.setLayout(code_paneLayout);
        code_paneLayout.setHorizontalGroup(
            code_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(code_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(code_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(code_paneLayout.createSequentialGroup()
                        .addComponent(codeUNITE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, code_paneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)))
                .addComponent(cc_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        code_paneLayout.setVerticalGroup(
            code_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(code_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codeUNITE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(cc_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg.add(jRadioButton1);
        jRadioButton1.setText("Insertion");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        bg.add(jRadioButton2);
        jRadioButton2.setText("Suppression");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        inser_button.setText("insert ↑");
        inser_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inser_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inser_paneLayout = new javax.swing.GroupLayout(inser_pane);
        inser_pane.setLayout(inser_paneLayout);
        inser_paneLayout.setHorizontalGroup(
            inser_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inser_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inser_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inser_paneLayout.setVerticalGroup(
            inser_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inser_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inser_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        supp_button.setText("Supprimer ❌");
        supp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_buttonActionPerformed(evt);
            }
        });
        supp_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supp_buttonKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout supp_paneLayout = new javax.swing.GroupLayout(supp_pane);
        supp_pane.setLayout(supp_paneLayout);
        supp_paneLayout.setHorizontalGroup(
            supp_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supp_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supp_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        supp_paneLayout.setVerticalGroup(
            supp_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supp_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supp_button)
                .addContainerGap())
        );

        jLabel1.setText("Matricule");

        matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculeActionPerformed(evt);
            }
        });
        matricule.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matriculeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                matriculeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                matriculeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout mat_paneLayout = new javax.swing.GroupLayout(mat_pane);
        mat_pane.setLayout(mat_paneLayout);
        mat_paneLayout.setHorizontalGroup(
            mat_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mat_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mat_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mat_paneLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)))
                .addContainerGap())
        );
        mat_paneLayout.setVerticalGroup(
            mat_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mat_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(jRadioButton3);
        jRadioButton3.setText("Changement");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        nom_pane.setPreferredSize(new java.awt.Dimension(140, 62));

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomKeyTyped(evt);
            }
        });

        jLabel6.setText("Nom");

        javax.swing.GroupLayout nom_paneLayout = new javax.swing.GroupLayout(nom_pane);
        nom_pane.setLayout(nom_paneLayout);
        nom_paneLayout.setHorizontalGroup(
            nom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nom_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nom_paneLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nom_paneLayout.setVerticalGroup(
            nom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nom_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        change_pane.setPreferredSize(new java.awt.Dimension(89, 45));

        change_button.setText("Changer");
        change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout change_paneLayout = new javax.swing.GroupLayout(change_pane);
        change_pane.setLayout(change_paneLayout);
        change_paneLayout.setHorizontalGroup(
            change_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, change_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(change_button)
                .addContainerGap())
        );
        change_paneLayout.setVerticalGroup(
            change_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(change_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(change_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("La matricule a plusieur code svp precisez");

        javax.swing.GroupLayout modulename_paneLayout = new javax.swing.GroupLayout(modulename_pane);
        modulename_pane.setLayout(modulename_paneLayout);
        modulename_paneLayout.setHorizontalGroup(
            modulename_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );
        modulename_paneLayout.setVerticalGroup(
            modulename_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modulename_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mat_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nom_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(code_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(exist_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(supp_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(223, 223, 223)
                                .addComponent(inser_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(change_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(modulename_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton1)
                        .addGap(48, 48, 48)
                        .addComponent(jRadioButton2)
                        .addGap(48, 48, 48)
                        .addComponent(jRadioButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mat_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(code_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supp_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inser_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modulename_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exist_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codeUNITEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeUNITEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeUNITEActionPerformed

    private void codeUNITEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeUNITEKeyReleased
        // TODO add your handling code here:
        if((noteEX.getText().equals(""))||(codeUNITE.getText().equals(""))||(matricule.getText().equals(""))||(noteCC.getText().equals(""))||(noteTP.getText().equals(""))){
            inser_button.setEnabled(false);
        }
        else {
            inser_button.setEnabled(true);
        }

        /**************** change button ******//////////////
        try{
           
           Connection cn = JavaConnectDb.ConnecrDb();
           Statement myStmt3 = cn.createStatement();
           if(matricule.getText().equals("")){
               
           }else{
           PreparedStatement st = cn.prepareStatement("SELECT *  FROM etudiantunite WHERE code_unite = ? and matricule_etu=?");
           st.setString(1,codeUNITE.getText());
           st.setString(2,matricule.getText());
           ResultSet myRs1 = st.executeQuery();
           if(myRs1.next()){
                noteCC.setText(myRs1.getString("note_cc"));
                noteTP.setText(myRs1.getString("note_tp"));
                noteEX.setText(myRs1.getString("note_examen"));
                change_button.setEnabled(true);
                modulename_pane.setVisible(false);
           }else{
               noteCC.setText("");
                noteTP.setText("");
                noteEX.setText("");
                change_button.setEnabled(false);
           }

                
           }
           
        }
        catch (Exception e){
            
        }
       
    }//GEN-LAST:event_codeUNITEKeyReleased

    private void codeUNITEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeUNITEKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_codeUNITEKeyTyped

    private void noteCCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noteCCKeyReleased
        // TODO add your handling code here:
        if((noteEX.getText().equals(""))||(noteCC.getText().equals(""))||(matricule.getText().equals(""))||(codeUNITE.getText().equals(""))||(noteTP.getText().equals(""))){
            inser_button.setEnabled(false);
        }
        else {
            inser_button.setEnabled(true);}

    }//GEN-LAST:event_noteCCKeyReleased

    private void noteCCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noteCCKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_noteCCKeyTyped

    private void noteTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noteTPActionPerformed

    private void noteTPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noteTPKeyReleased
        // TODO add your handling code here:
        if((noteEX.getText().equals(""))||(noteTP.getText().equals(""))||(matricule.getText().equals(""))||(noteCC.getText().equals(""))||(codeUNITE.getText().equals(""))){
            inser_button.setEnabled(false);
        }
        else {
            inser_button.setEnabled(true);}
    }//GEN-LAST:event_noteTPKeyReleased

    private void noteTPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noteTPKeyTyped
        // TODO add your handling code here:$

    }//GEN-LAST:event_noteTPKeyTyped

    private void noteEXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noteEXKeyReleased
        // TODO add your handling code here:
        if((noteEX.getText().equals(""))||(noteTP.getText().equals(""))||(matricule.getText().equals(""))||(noteCC.getText().equals(""))||(codeUNITE.getText().equals(""))){
            inser_button.setEnabled(false);
        }
        else {
            inser_button.setEnabled(true);}

    }//GEN-LAST:event_noteEXKeyReleased

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        mat_pane.setVisible(true);
        change_pane.setVisible(false);
        code_pane.setVisible(true);
        cc_pane.setVisible(true);
        tp_pane.setVisible(true);
        examen_pane.setVisible(true);
        supp_pane.setVisible(false);
        inser_pane.setVisible(true);
        nom_pane.setVisible(false);
        codeUNITE.setText("");
        noteCC.setText("");
        noteTP.setText("");
        matricule.setText("");
        noteEX.setText("");

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        codeUNITE.setText("");
        change_pane.setVisible(false);
        nom.setText("");
        noteEX.setText("");
        noteCC.setText("");
        noteTP.setText("");
        matricule.setText("");
        mat_pane.setVisible(true);
        code_pane.setVisible(false);
        examen_pane.setVisible(false);
        cc_pane.setVisible(false);
        tp_pane.setVisible(false);
        nom_pane.setVisible(true);
        inser_pane.setVisible(false);
        supp_pane.setVisible(true);

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void inser_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inser_buttonActionPerformed
        // TODO add your handling code here:
        try {
            
            String sql ="insert into etudiantunite(matricule_etu,code_unite,note_cc,note_tp,note_examen) values (?,?,?,?,?)";
            PreparedStatement ps=cn.prepareStatement(sql);
            ps.setInt(1,Integer.parseInt(matricule.getText()));
            ps.setString(2,codeUNITE.getText());
            ps.setString(3,noteCC.getText());
            ps.setString(4,noteTP.getText());
            ps.setString(5,noteEX.getText());
  
            ps.executeUpdate();
            refresh();
            JOptionPane.showMessageDialog(this,"saved successfully");
            codeUNITE.setText("");
            noteCC.setText("");
            noteTP.setText("");
            matricule.setText("");
            noteEX.setText("");

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_inser_buttonActionPerformed

    private void supp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = JavaConnectDb.ConnecrDb();
            Statement myStmt = cn.createStatement();
            ResultSet myRs = myStmt.executeQuery("select * from etudiant");
            
            if (matricule.getText().equals("")){
                int matri = 0;
                int i = 0;
                while(myRs.next()){
                    if(nom.getText().equals(myRs.getString("nom_etu"))){
                        matri = myRs.getInt("matricule_etu");
                        i++;
                    }}
                
                PreparedStatement st1 = cn.prepareStatement("DELETE FROM etudiantunite WHERE matricule_etu ="+Integer.toString(matri));
               
                if (i>1){
                    exist_pane.setVisible(true);
                }else{
                    st1.executeUpdate();

                    nom.setText("");
                    supp_button.setEnabled(false);
                    if (i == 0){
                        JOptionPane.showMessageDialog(this,"le nom n'existe pas ! ");
                    }else{
                        JOptionPane.showMessageDialog(this,"deleted successfully");
                    }
                }
            }else{

                exist_pane.setVisible(false);
                PreparedStatement st2 = cn.prepareStatement("DELETE FROM etudiantunite WHERE matricule_etu=?");
                st2.setString(1,matricule.getText());
                Statement myStmt2 = cn.createStatement();
                ResultSet myRs2 = myStmt.executeQuery("select * from etudiantunite where matricule_etu ="+matricule.getText());
                if (myRs2.next()){
                    st2.executeUpdate();
                JOptionPane.showMessageDialog(this,"deleted successfully");
                matricule.setText("");
                nom.setText("");
                }else{
                    JOptionPane.showMessageDialog(this,"La matricule n'existe pas dans ce tableau");
                }
                
            }
            refresh();

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }

    }//GEN-LAST:event_supp_buttonActionPerformed

    private void supp_buttonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supp_buttonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supp_buttonKeyReleased

    private void matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculeActionPerformed

    private void matriculeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculeKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_matriculeKeyPressed

    private void matriculeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculeKeyReleased
        // TODO add your handling code here:
        if((noteEX.getText().equals(""))||(matricule.getText().equals(""))||(codeUNITE.getText().equals(""))||(noteCC.getText().equals(""))||(noteTP.getText().equals(""))){
            inser_button.setEnabled(false);
            modulename_pane.setVisible(false);
        }
        else {
            inser_button.setEnabled(true);}
        /********** change button ***********/
        try{
            Connection cn = JavaConnectDb.ConnecrDb();
            Statement myStmt3 = cn.createStatement();
            Statement myStmt4 = cn.createStatement();
            ResultSet myRs3 = myStmt3.executeQuery("select * from etudiant where matricule_etu = "+matricule.getText());
            ResultSet myRs4 = myStmt4.executeQuery("select * from etudiantunite where matricule_etu = "+matricule.getText());
            if(myRs3.next()) {
                nom.setText(myRs3.getString("nom_etu"));
                
                supp_button.setEnabled(true);
             
            }else{
                supp_button.setEnabled(false);
                   nom.setText("");
                
            }
            int i = 0;
            if(myRs4.next()){
                while(myRs4.next()){
                    i++;
                }
                if (i>0){
                    modulename_pane.setVisible(true);
                }else{
                    codeUNITE.setText(myRs4.getString("code_unite"));
                noteCC.setText(myRs4.getString("note_cc"));
                noteTP.setText(myRs4.getString("note_tp"));
                noteEX.setText(myRs4.getString("note_examen"));
                   change_button.setEnabled(true);
                    modulename_pane.setVisible(false);
                }}
              /*   */
          /**************** if code_unite is filled **********/
          if(codeUNITE.getText().equals("")){
           
           }else{
           PreparedStatement st = cn.prepareStatement("SELECT *  FROM etudiantunite WHERE code_unite = ? and matricule_etu=?");
           st.setString(1,codeUNITE.getText());
           st.setString(2,matricule.getText());
           ResultSet myRs1 = st.executeQuery();
           if(myRs1.next()){
                noteCC.setText(myRs1.getString("note_cc"));
                noteTP.setText(myRs1.getString("note_tp"));
                noteEX.setText(myRs1.getString("note_examen"));
                change_button.setEnabled(true);
           }else{
               noteCC.setText("");
                noteTP.setText("");
                noteEX.setText("");
                change_button.setEnabled(false);
           }

                
           }

        }catch(Exception e){

        }
    }//GEN-LAST:event_matriculeKeyReleased

    private void matriculeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculeKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_matriculeKeyTyped

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        codeUNITE.setText("");
        
        nom.setText("");
        noteEX.setText("");
        noteCC.setText("");
        noteTP.setText("");
        matricule.setText("");
        mat_pane.setVisible(true);
        code_pane.setVisible(true);
        examen_pane.setVisible(true);
        cc_pane.setVisible(true);
        tp_pane.setVisible(true);
        nom_pane.setVisible(false);
        inser_pane.setVisible(false);
        supp_pane.setVisible(false);
        change_pane.setVisible(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyReleased
        // TODO add your handling code here:
        if((nom.getText().equals(""))){
        supp_button.setEnabled(false); 
    }
    else {
        supp_button.setEnabled(true);}

        /**************** supp button ******//////////////
        if((nom.getText().equals(""))){
            supp_button.setEnabled(false);
        }
        else {
            supp_button.setEnabled(true);}
    }//GEN-LAST:event_nomKeyReleased

    private void nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_nomKeyTyped

    private void change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = JavaConnectDb.ConnecrDb();
          
           PreparedStatement st = cn.prepareStatement("UPDATE etudiantunite Set note_cc = ? , note_tp = ? , note_examen = ? where matricule_etu = ? and code_unite = ?");
           st.setString(1,noteCC.getText());
           st.setString(2,noteTP.getText());
           st.setString(3,noteEX.getText());
           st.setString(4,matricule.getText());
           st.setString(5,codeUNITE.getText());
            st.executeUpdate();
            refresh();
            codeUNITE.setText("");
            noteCC.setText("");
            noteTP.setText("");
            //matricule.setText("");
            noteEX.setText("");
            JOptionPane.showMessageDialog(this,"changé avec succès");
         }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
        
    }//GEN-LAST:event_change_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtudiantUnite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtudiantUnite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtudiantUnite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtudiantUnite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
Connection cn = JavaConnectDb.ConnecrDb();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EtudiantUnite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aaa;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JPanel cc_pane;
    private javax.swing.JButton change_button;
    private javax.swing.JPanel change_pane;
    private javax.swing.JTextField codeUNITE;
    private javax.swing.JPanel code_pane;
    private javax.swing.JPanel examen_pane;
    private javax.swing.JPanel exist_pane;
    private javax.swing.JButton inser_button;
    private javax.swing.JPanel inser_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mat_pane;
    private javax.swing.JTextField matricule;
    private javax.swing.JPanel modulename_pane;
    private javax.swing.JTextField nom;
    private javax.swing.JPanel nom_pane;
    private javax.swing.JTextField noteCC;
    private javax.swing.JTextField noteEX;
    private javax.swing.JTextField noteTP;
    private javax.swing.JButton supp_button;
    private javax.swing.JPanel supp_pane;
    private javax.swing.JTable table1;
    private javax.swing.JPanel tp_pane;
    // End of variables declaration//GEN-END:variables
}
