/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseprojet;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author El Mysto
 */
public class Etudiant extends javax.swing.JFrame {
     Connection cn = JavaConnectDb.ConnecrDb();

    /**
     * Creates new form Etudiant
     */
    public Etudiant() {
        initComponents();
        inser_button.setEnabled(false);
        supp_button.setEnabled(false);
         mat_pane.setVisible(false);
        nom_pane.setVisible(false);
        prenom_pane.setVisible(false);
        date_pane.setVisible(false);
         inser_pane.setVisible(false);
         supp_pane.setVisible(false);
         exist_pane.setVisible(false);
         change_pane.setVisible(false);
        refresh();
        }
public void refresh(){
             try{
            Connection cn = JavaConnectDb.ConnecrDb();
           //   Statement myStmt2 = cn.createStatement();
             //  myStmt2.executeQuery("Alter Session set NLS_DATE_FORMAT = 'DD/MM/YYYY'");
            PreparedStatement ps=cn.prepareStatement("select * from etudiant");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)table1.getModel();
            tm.setRowCount(0);
            while(rs.next()){
      Object o[]={rs.getInt("Matricule_etu"),rs.getString("nom_etu"),rs.getString("prenom_etu"),rs.getDate("date_naissance"),rs.getString("adresse")};
      tm.addRow(o);
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
        }
public String saving(String x){
    return x;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("jdbc:oracle:thin:@localhost:1521:orclPU").createEntityManager();
        etudiant_1Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM Etudiant_1 e");
        etudiant_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : etudiant_1Query.getResultList();
        group1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        inser_pane = new javax.swing.JPanel();
        inser_button = new javax.swing.JButton();
        supp_pane = new javax.swing.JPanel();
        supp_button = new javax.swing.JButton();
        mat_pane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricule = new javax.swing.JTextField();
        nom_pane = new javax.swing.JPanel();
        nom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prenom_pane = new javax.swing.JPanel();
        prenom = new javax.swing.JTextField();
        aaa = new javax.swing.JLabel();
        date_pane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        adress_pane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        adress = new javax.swing.JTextField();
        exist_pane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        change_rad = new javax.swing.JRadioButton();
        change_pane = new javax.swing.JPanel();
        change_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        table1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matricule", "Nom", "Prénom", "Date_Naissance", "Adresse"
            }
        ));
        jScrollPane2.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(3).setHeaderValue("Date_Naissance");
            table1.getColumnModel().getColumn(4).setHeaderValue("Adresse");
        }

        group1.add(jRadioButton1);
        jRadioButton1.setText("Insertion");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        group1.add(jRadioButton2);
        jRadioButton2.setText("Suppression");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        inser_button.setText("insert ↑");
        inser_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inser_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inser_paneLayout = new javax.swing.GroupLayout(inser_pane);
        inser_pane.setLayout(inser_paneLayout);
        inser_paneLayout.setHorizontalGroup(
            inser_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inser_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inser_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inser_paneLayout.setVerticalGroup(
            inser_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inser_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inser_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        supp_button.setText("Supprimer ❌");
        supp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_buttonActionPerformed(evt);
            }
        });
        supp_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supp_buttonKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout supp_paneLayout = new javax.swing.GroupLayout(supp_pane);
        supp_pane.setLayout(supp_paneLayout);
        supp_paneLayout.setHorizontalGroup(
            supp_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supp_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supp_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        supp_paneLayout.setVerticalGroup(
            supp_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supp_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supp_button)
                .addContainerGap())
        );

        jLabel1.setText("Matricule");

        matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculeActionPerformed(evt);
            }
        });
        matricule.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matriculeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                matriculeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                matriculeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout mat_paneLayout = new javax.swing.GroupLayout(mat_pane);
        mat_pane.setLayout(mat_paneLayout);
        mat_paneLayout.setHorizontalGroup(
            mat_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mat_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mat_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mat_paneLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)))
                .addContainerGap())
        );
        mat_paneLayout.setVerticalGroup(
            mat_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mat_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomKeyTyped(evt);
            }
        });

        jLabel2.setText("Nom");

        prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prenomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prenomKeyTyped(evt);
            }
        });

        aaa.setText("Prenom");

        jLabel4.setText("Date");

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateKeyTyped(evt);
            }
        });

        adress_pane.setPreferredSize(new java.awt.Dimension(140, 62));

        jLabel5.setText("Adresse");

        adress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adressKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout adress_paneLayout = new javax.swing.GroupLayout(adress_pane);
        adress_pane.setLayout(adress_paneLayout);
        adress_paneLayout.setHorizontalGroup(
            adress_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adress_paneLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adress_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        adress_paneLayout.setVerticalGroup(
            adress_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adress_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout date_paneLayout = new javax.swing.GroupLayout(date_pane);
        date_pane.setLayout(date_paneLayout);
        date_paneLayout.setHorizontalGroup(
            date_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(date_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(date_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, date_paneLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(48, 48, 48)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adress_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        date_paneLayout.setVerticalGroup(
            date_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(date_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(adress_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout prenom_paneLayout = new javax.swing.GroupLayout(prenom_pane);
        prenom_pane.setLayout(prenom_paneLayout);
        prenom_paneLayout.setHorizontalGroup(
            prenom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prenom_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prenom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prenom_paneLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(aaa))
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        prenom_paneLayout.setVerticalGroup(
            prenom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prenom_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aaa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(date_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout nom_paneLayout = new javax.swing.GroupLayout(nom_pane);
        nom_pane.setLayout(nom_paneLayout);
        nom_paneLayout.setHorizontalGroup(
            nom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nom_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(nom_paneLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prenom_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nom_paneLayout.setVerticalGroup(
            nom_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nom_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(prenom_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Ce nom existe plus d'une fois , svp entrer son matricule.");

        javax.swing.GroupLayout exist_paneLayout = new javax.swing.GroupLayout(exist_pane);
        exist_pane.setLayout(exist_paneLayout);
        exist_paneLayout.setHorizontalGroup(
            exist_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exist_paneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        exist_paneLayout.setVerticalGroup(
            exist_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exist_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        group1.add(change_rad);
        change_rad.setText("Changement");
        change_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_radActionPerformed(evt);
            }
        });

        change_pane.setPreferredSize(new java.awt.Dimension(89, 45));

        change_button.setText("Changer");
        change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout change_paneLayout = new javax.swing.GroupLayout(change_pane);
        change_pane.setLayout(change_paneLayout);
        change_paneLayout.setHorizontalGroup(
            change_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, change_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(change_button)
                .addContainerGap())
        );
        change_paneLayout.setVerticalGroup(
            change_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(change_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(change_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton1)
                        .addGap(48, 48, 48)
                        .addComponent(jRadioButton2)
                        .addGap(48, 48, 48)
                        .addComponent(change_rad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(change_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supp_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(223, 223, 223)
                                .addComponent(inser_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mat_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nom_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(exist_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(change_rad))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mat_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supp_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inser_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exist_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(change_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inser_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inser_buttonActionPerformed
        // TODO add your handling code here:
        try {
      
        String sql ="insert into etudiant(matricule_etu,nom_etu,prenom_etu,date_naissance,adresse) values (?,?,?,?,?)";
        PreparedStatement ps=cn.prepareStatement(sql);
        ps.setInt(1,Integer.parseInt(matricule.getText()));
        ps.setString(2,nom.getText());
        ps.setString(3,prenom.getText());
        ps.setDate(4,(java.sql.Date.valueOf(date.getText())));
        ps.setString(5,adress.getText());
    
        ps.executeUpdate();
        refresh();
        nom.setText("");
        prenom.setText("");
        date.setText("");
        matricule.setText("");
        adress.setText("");
        
        JOptionPane.showMessageDialog(this,"saved successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_inser_buttonActionPerformed

    private void supp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_buttonActionPerformed
        // TODO add your handling code here:
        try {
        Connection cn = JavaConnectDb.ConnecrDb();
        PreparedStatement st = cn.prepareStatement("DELETE FROM etudiant WHERE nom_etu = ? and matricule_etu=?");
        Statement myStmt = cn.createStatement();
        ResultSet myRs = myStmt.executeQuery("select * from etudiant");
        st.setString(1,nom.getText());
        st.setString(2,matricule.getText());
        if (matricule.getText().equals("")){
        PreparedStatement st1 = cn.prepareStatement("DELETE FROM etudiant WHERE nom_etu = ?");
        st1.setString(1,nom.getText());
        int i=0;
	while(myRs.next()) {
	if(nom.getText().equals(myRs.getString("nom_etu"))){
            i++;}
        }
           if (i>1){
            exist_pane.setVisible(true);
           }else{
               st1.executeUpdate();
               
               nom.setText("");
               supp_button.setEnabled(false);
               if (i == 0){
                   JOptionPane.showMessageDialog(this,"it doesnt exist yaw");
               }else{
                   JOptionPane.showMessageDialog(this,"deleted successfully");
               }
           }
     }else{
   
            exist_pane.setVisible(false);
            PreparedStatement st2 = cn.prepareStatement("DELETE FROM etudiant WHERE nom_etu = ? and matricule_etu=?");
            
        st2.setString(1,nom.getText());
        st2.setString(2,matricule.getText());
        st2.executeUpdate();
        refresh();
        JOptionPane.showMessageDialog(this,"deleted successfully");
        matricule.setText("");
        nom.setText("");
        }
        
        
         
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
        
    }//GEN-LAST:event_supp_buttonActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        change_pane.setVisible(false);
        mat_pane.setVisible(true);
        nom_pane.setVisible(true);
        prenom_pane.setVisible(true);
        date_pane.setVisible(true);
        adress_pane.setVisible(true);
        supp_pane.setVisible(false);
        inser_pane.setVisible(true);
        nom.setText("");
        prenom.setText("");
        date.setText("");
        matricule.setText("");
        adress.setText("");
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        change_pane.setVisible(false);
        supp_button.setEnabled(false);
        nom.setText("");
        adress.setText("");
        prenom.setText("");
        date.setText("");
        matricule.setText("");
        mat_pane.setVisible(true);
        nom_pane.setVisible(true);
        adress_pane.setVisible(false);
        prenom_pane.setVisible(false);
        
        date_pane.setVisible(false);
        
        inser_pane.setVisible(false);
        supp_pane.setVisible(true);
       
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nomActionPerformed

    private void matriculeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculeKeyReleased
        // TODO add your handling code here:
        if((adress.getText().equals(""))||(matricule.getText().equals(""))||(nom.getText().equals(""))||(prenom.getText().equals(""))||(date.getText().equals(""))){
        inser_button.setEnabled(false); 
    }
    else {
        inser_button.setEnabled(true);}
       try{
        Connection cn = JavaConnectDb.ConnecrDb();
        Statement myStmt3 = cn.createStatement();
            ResultSet myRs3 = myStmt3.executeQuery("select * from etudiant where matricule_etu = "+matricule.getText());
            if(myRs3.next()) {
                nom.setText(myRs3.getString("nom_etu"));
                supp_button.setEnabled(true);
	}else{
                supp_button.setEnabled(false);
                nom.setText("");
            }
            
            
            
           
        }catch(Exception e){
            
        }
       /*********** CHANGE BUTTON **************/
            
              
       /******************** ON THE CHANGE RADBUTTON ******************/
       try{ 
           
        if(change_rad.isSelected()){
            Connection cn = JavaConnectDb.ConnecrDb();
            PreparedStatement st50 = cn.prepareStatement("SELECT *  FROM etudiant WHERE matricule_etu = ? ");
            st50.setInt(1,Integer.parseInt(matricule.getText()));
            ResultSet myRs50 = st50.executeQuery();
            if(myRs50.next()) {
                nom_pane.setVisible(true);  
                prenom_pane.setVisible(true); 
                date_pane.setVisible(true); 
                adress_pane.setVisible(true); 
                
                nom.setText(myRs50.getString("nom_etu"));
                prenom.setText(myRs50.getString("prenom_etu"));
                date.setText(myRs50.getDate("date_naissance").toString());
                adress.setText(myRs50.getString("adresse"));
                
                change_button.setEnabled(true);
            }else{
                nom_pane.setVisible(false);  
                prenom_pane.setVisible(false); 
                date_pane.setVisible(false); 
                adress_pane.setVisible(false);  
                change_button.setEnabled(false);
                nom.setText("");
                prenom.setText("");
                date.setText("");
                adress.setText("");
            }
              
          }

        }catch(Exception e){
         
        }
    }//GEN-LAST:event_matriculeKeyReleased
    
    private void nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyReleased
        // TODO add your handling code here:
        if((adress.getText().equals(""))||(nom.getText().equals(""))||(matricule.getText().equals(""))||(prenom.getText().equals(""))||(date.getText().equals(""))){
        inser_button.setEnabled(false); 
    }
    else {
        inser_button.setEnabled(true);
    }
        
        /**************** supp button ******//////////////
        if((nom.getText().equals(""))){
        supp_button.setEnabled(false); 
    }
    else {
        supp_button.setEnabled(true);}
    }//GEN-LAST:event_nomKeyReleased

    private void prenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomKeyReleased
        // TODO add your handling code here:
        if((adress.getText().equals(""))||(prenom.getText().equals(""))||(matricule.getText().equals(""))||(nom.getText().equals(""))||(date.getText().equals(""))){
        inser_button.setEnabled(false); 
    }
    else {
        inser_button.setEnabled(true);}
       
    }//GEN-LAST:event_prenomKeyReleased
    
        
    private void dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyReleased
        // TODO add your handling code here:   
        if((adress.getText().equals(""))||(date.getText().equals(""))||(matricule.getText().equals(""))||(prenom.getText().equals(""))||(nom.getText().equals(""))){
        inser_button.setEnabled(false); 
    }
    else {
        inser_button.setEnabled(true);}  
    }//GEN-LAST:event_dateKeyReleased
    
    
    private void matriculeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculeKeyTyped
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_matriculeKeyTyped

    private void nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nomKeyTyped

    private void prenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomKeyTyped
        // TODO add your handling code here:
           
    }//GEN-LAST:event_prenomKeyTyped

    private void dateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyTyped
        // TODO add your handling code here:$
        
    }//GEN-LAST:event_dateKeyTyped

    private void matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculeActionPerformed

    private void supp_buttonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supp_buttonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supp_buttonKeyReleased

    private void matriculeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculeKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_matriculeKeyPressed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void adressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adressKeyReleased
        // TODO add your handling code here:
        if((adress.getText().equals(""))||(date.getText().equals(""))||(matricule.getText().equals(""))||(prenom.getText().equals(""))||(nom.getText().equals(""))){
        inser_button.setEnabled(false); 
    }
    else {
        inser_button.setEnabled(true);}  
           
    }//GEN-LAST:event_adressKeyReleased

    private void change_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_radActionPerformed
        // TODO add your handling code here:

        nom.setText("");
        matricule.setText("");
        prenom.setText("");
        date.setText("");
        adress.setText("");
        mat_pane.setVisible(true);
        nom_pane.setVisible(false);
        prenom_pane.setVisible(false);
        date_pane.setVisible(false);
        adress_pane.setVisible(false);
        inser_pane.setVisible(false);
        supp_pane.setVisible(false);
        change_pane.setVisible(true);
        change_button.setEnabled(false);
    }//GEN-LAST:event_change_radActionPerformed

    private void change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = JavaConnectDb.ConnecrDb();

            PreparedStatement st = cn.prepareStatement("UPDATE etudiant Set nom_etu = ? , prenom_etu = ? , adresse = ? , date_naissance = ? where matricule_etu = ?");
            st.setString(1,nom.getText());
            st.setString(2,prenom.getText());
            st.setString(3,adress.getText());
            
            st.setString(5,matricule.getText());
            
            st.setDate(4,(java.sql.Date.valueOf(date.getText())));
            st.executeUpdate();
            refresh();
            nom.setText("");
            prenom.setText("");
            adress.setText("");
            //matricule.setText("");
            date.setText("");
            JOptionPane.showMessageDialog(this,"changé avec succès");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }

    }//GEN-LAST:event_change_buttonActionPerformed
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
          ButtonGroup bg = new ButtonGroup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etudiant().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aaa;
    private javax.swing.JTextField adress;
    private javax.swing.JPanel adress_pane;
    private javax.swing.JButton change_button;
    private javax.swing.JPanel change_pane;
    private javax.swing.JRadioButton change_rad;
    private javax.swing.JTextField date;
    private javax.swing.JPanel date_pane;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<databaseprojet.Etudiant_1> etudiant_1List;
    private javax.persistence.Query etudiant_1Query;
    private javax.swing.JPanel exist_pane;
    private javax.swing.ButtonGroup group1;
    private javax.swing.JButton inser_button;
    private javax.swing.JPanel inser_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mat_pane;
    private javax.swing.JTextField matricule;
    private javax.swing.JTextField nom;
    private javax.swing.JPanel nom_pane;
    private javax.swing.JTextField prenom;
    private javax.swing.JPanel prenom_pane;
    private javax.swing.JButton supp_button;
    private javax.swing.JPanel supp_pane;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
