/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseprojet;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Panel;
import java.awt.Toolkit;
import javax.swing.JPanel;
import java.lang.Thread;
import java.lang.String;
import java.lang.Float;
import java.lang.Exception;
import javax.swing.JOptionPane;

/**
 *
 * @author El Mysto
 */
public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdmin
     */
    public HomeAdmin() {
        initComponents();
        setBackground(new Color(0,0,0,0));
       
       Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
       this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
       //call.removeAll();
         //  call.repaint();
           WelcomePage wp= new WelcomePage ();
                call.add(wp.getContentPane());
        
      
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        enseignant_pane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        home_pane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etudiant_pane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codeunite_pane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        unite_pane = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        req1_pane = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        req2_pane = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        req3_pane = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        req4_pane = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        req4_paneee = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        req4_paneee2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        call = new javax.swing.JPanel();
        start = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1213, 660));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enseignant_pane.setBackground(new java.awt.Color(64, 43, 100));
        enseignant_pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enseignant_paneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enseignant_paneMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseprojet/Icons/icons8-studenttt-center-30.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Les enseignants");

        javax.swing.GroupLayout enseignant_paneLayout = new javax.swing.GroupLayout(enseignant_pane);
        enseignant_pane.setLayout(enseignant_paneLayout);
        enseignant_paneLayout.setHorizontalGroup(
            enseignant_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enseignant_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        enseignant_paneLayout.setVerticalGroup(
            enseignant_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(enseignant_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(enseignant_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 50));

        home_pane.setBackground(new java.awt.Color(85, 65, 118));
        home_pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_paneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_paneMousePressed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseprojet/Icons/icons8-home-30.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Home Page");

        javax.swing.GroupLayout home_paneLayout = new javax.swing.GroupLayout(home_pane);
        home_pane.setLayout(home_paneLayout);
        home_paneLayout.setHorizontalGroup(
            home_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        home_paneLayout.setVerticalGroup(
            home_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(home_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(home_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 50));

        etudiant_pane.setBackground(new java.awt.Color(64, 43, 100));
        etudiant_pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etudiant_paneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                etudiant_paneMousePressed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseprojet/Icons/icons8-user-male-30.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Les etudiants");

        javax.swing.GroupLayout etudiant_paneLayout = new javax.swing.GroupLayout(etudiant_pane);
        etudiant_pane.setLayout(etudiant_paneLayout);
        etudiant_paneLayout.setHorizontalGroup(
            etudiant_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etudiant_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        etudiant_paneLayout.setVerticalGroup(
            etudiant_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(etudiant_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(etudiant_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 50));

        codeunite_pane.setBackground(new java.awt.Color(64, 43, 100));
        codeunite_pane.setPreferredSize(new java.awt.Dimension(220, 50));
        codeunite_pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codeunite_paneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                codeunite_paneMousePressed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseprojet/Icons/icons8-important-note-30.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("EtudiantUnite");

        javax.swing.GroupLayout codeunite_paneLayout = new javax.swing.GroupLayout(codeunite_pane);
        codeunite_pane.setLayout(codeunite_paneLayout);
        codeunite_paneLayout.setHorizontalGroup(
            codeunite_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(codeunite_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        codeunite_paneLayout.setVerticalGroup(
            codeunite_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(codeunite_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(codeunite_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 50));

        unite_pane.setBackground(new java.awt.Color(64, 43, 100));
        unite_pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unite_paneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unite_paneMousePressed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseprojet/Icons/icons8-tinder-30.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Unite");

        javax.swing.GroupLayout unite_paneLayout = new javax.swing.GroupLayout(unite_pane);
        unite_pane.setLayout(unite_paneLayout);
        unite_paneLayout.setHorizontalGroup(
            unite_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unite_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        unite_paneLayout.setVerticalGroup(
            unite_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(unite_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(unite_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 220, 50));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 140, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("Administrateur");
        sidepane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        req1_pane.setBackground(new java.awt.Color(64, 43, 100));
        req1_pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                req1_paneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                req1_paneMousePressed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseprojet/Icons/icons8-inactive-state-30.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("ReQuet 1");

        javax.swing.GroupLayout req1_paneLayout = new javax.swing.GroupLayout(req1_pane);
        req1_pane.setLayout(req1_paneLayout);
        req1_paneLayout.setHorizontalGroup(
            req1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(req1_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        req1_paneLayout.setVerticalGroup(
            req1_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(req1_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(req1_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 220, 50));

        req2_pane.setBackground(new java.awt.Color(64, 43, 100));
        req2_pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                req2_paneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                req2_paneMousePressed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseprojet/Icons/icons8-inactive-state-30.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("ReQuet 2");

        javax.swing.GroupLayout req2_paneLayout = new javax.swing.GroupLayout(req2_pane);
        req2_pane.setLayout(req2_paneLayout);
        req2_paneLayout.setHorizontalGroup(
            req2_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(req2_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        req2_paneLayout.setVerticalGroup(
            req2_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(req2_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(req2_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 220, 50));

        req3_pane.setBackground(new java.awt.Color(64, 43, 100));
        req3_pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                req3_paneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                req3_paneMousePressed(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseprojet/Icons/icons8-inactive-state-30.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("ReQuet 3");

        javax.swing.GroupLayout req3_paneLayout = new javax.swing.GroupLayout(req3_pane);
        req3_pane.setLayout(req3_paneLayout);
        req3_paneLayout.setHorizontalGroup(
            req3_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(req3_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        req3_paneLayout.setVerticalGroup(
            req3_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(req3_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(req3_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 220, 50));

        req4_pane.setBackground(new java.awt.Color(64, 43, 100));
        req4_pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                req4_paneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                req4_paneMousePressed(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseprojet/Icons/icons8-inactive-state-30.png"))); // NOI18N

        req4_paneee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        req4_paneee.setForeground(new java.awt.Color(204, 204, 204));
        req4_paneee.setText("ReQuet 4");

        javax.swing.GroupLayout req4_paneLayout = new javax.swing.GroupLayout(req4_pane);
        req4_pane.setLayout(req4_paneLayout);
        req4_paneLayout.setHorizontalGroup(
            req4_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(req4_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(req4_paneee, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        req4_paneLayout.setVerticalGroup(
            req4_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(req4_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(req4_paneee, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(req4_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 220, 50));

        jPanel2.setBackground(new java.awt.Color(64, 43, 100));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        req4_paneee2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        req4_paneee2.setForeground(new java.awt.Color(204, 204, 204));
        req4_paneee2.setText("Change User");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\korus\\OneDrive\\Documents\\NetBeansProjects\\DatabaseProjet\\src\\databaseprojet\\Icons\\New folder\\icons8-change-user-28.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(req4_paneee2)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(req4_paneee2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 633, 220, 30));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 690));

        jPanel1.setBackground(new java.awt.Color(63, 11, 129));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 993, 140));

        call.setPreferredSize(new java.awt.Dimension(848, 345));

        start.setIcon(new javax.swing.ImageIcon("C:\\Users\\korus\\OneDrive\\Documents\\NetBeansProjects\\DatabaseProjet\\src\\databaseprojet\\Icons\\start.png")); // NOI18N
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout callLayout = new javax.swing.GroupLayout(call);
        call.setLayout(callLayout);
        callLayout.setHorizontalGroup(
            callLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, callLayout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addComponent(start)
                .addGap(399, 399, 399))
        );
        callLayout.setVerticalGroup(
            callLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, callLayout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(start)
                .addGap(179, 179, 179))
        );

        bg.add(call, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 993, 490));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\korus\\OneDrive\\Documents\\NetBeansProjects\\DatabaseProjet\\src\\databaseprojet\\Icons\\icons8-close-window-30.png")); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        bg.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 30, 30));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 659));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_paneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_paneMousePressed
        // TODO add your handling code here:
        setColor(home_pane);
        resetColor(etudiant_pane);
        resetColor(enseignant_pane);
        resetColor(codeunite_pane);
        resetColor(unite_pane);
        
                
    }//GEN-LAST:event_home_paneMousePressed

    private void etudiant_paneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etudiant_paneMousePressed
        // TODO add your handling code here:
        setColor(etudiant_pane);
        resetColor(enseignant_pane);
        resetColor(home_pane);
        resetColor(codeunite_pane);
        resetColor(unite_pane);
        resetColor(req1_pane);
        resetColor(req2_pane);
        resetColor(req4_pane);
        resetColor(req3_pane);
    }//GEN-LAST:event_etudiant_paneMousePressed

    private void enseignant_paneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enseignant_paneMousePressed
        // TODO add your handling code here:
        setColor(enseignant_pane);
        resetColor(home_pane);
        resetColor(etudiant_pane);
        resetColor(codeunite_pane);
        resetColor(unite_pane);
        resetColor(req1_pane);
        resetColor(req2_pane);
        resetColor(req4_pane);
        resetColor(req3_pane);
    }//GEN-LAST:event_enseignant_paneMousePressed

    private void codeunite_paneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codeunite_paneMousePressed
        // TODO add your handling code here:
        resetColor(enseignant_pane);
        resetColor(home_pane);
        resetColor(etudiant_pane);
        setColor(codeunite_pane);
        resetColor(unite_pane);
        resetColor(req1_pane);
        resetColor(req2_pane);
        resetColor(req4_pane);
        resetColor(req3_pane);
    }//GEN-LAST:event_codeunite_paneMousePressed

    private void unite_paneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unite_paneMousePressed
        // TODO add your handling code here:
        resetColor(enseignant_pane);
        resetColor(home_pane);
        resetColor(etudiant_pane);
        resetColor(codeunite_pane);
        resetColor(req1_pane);
        resetColor(req2_pane);
        resetColor(req4_pane);
        resetColor(req3_pane);
        setColor(unite_pane);
    }//GEN-LAST:event_unite_paneMousePressed

    private void etudiant_paneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etudiant_paneMouseClicked
        // TODO add your handling code here:
        call.removeAll();
           call.repaint();
            Etudiant etu = new Etudiant ();
                call.add(etu.getContentPane());
                 home_pane.setVisible(false);
    }//GEN-LAST:event_etudiant_paneMouseClicked

    private void req1_paneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_req1_paneMousePressed
        // TODO add your handling code here:
       setColor(req1_pane);
        resetColor(enseignant_pane);
        resetColor(home_pane);
        resetColor(codeunite_pane);
        resetColor(unite_pane);
        resetColor(req3_pane);
        resetColor(req2_pane);
        resetColor(etudiant_pane);
        resetColor(req4_pane);
    }//GEN-LAST:event_req1_paneMousePressed

    private void req2_paneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_req2_paneMousePressed
        // TODO add your handling code here:
        setColor(req2_pane);
        resetColor(enseignant_pane);
        resetColor(home_pane);
        resetColor(codeunite_pane);
        resetColor(unite_pane);
        resetColor(req1_pane);
        resetColor(req3_pane);
        resetColor(etudiant_pane);
        resetColor(req4_pane);
    }//GEN-LAST:event_req2_paneMousePressed

    private void req3_paneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_req3_paneMousePressed
        // TODO add your handling code here:
        
        setColor(req3_pane);
        resetColor(enseignant_pane);
        resetColor(home_pane);
        resetColor(codeunite_pane);
        resetColor(unite_pane);
        resetColor(req1_pane);
        resetColor(req2_pane);
        resetColor(etudiant_pane);
        resetColor(req4_pane);
        
    }//GEN-LAST:event_req3_paneMousePressed

    private void enseignant_paneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enseignant_paneMouseClicked
        // TODO add your handling code here:
        call.removeAll();
           call.repaint();
            Enseignant ens = new Enseignant ();
                call.add(ens.getContentPane());
                 home_pane.setVisible(false);
        
        
    }//GEN-LAST:event_enseignant_paneMouseClicked

    private void codeunite_paneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codeunite_paneMouseClicked
        // TODO add your handling code here:
        call.removeAll();
           call.repaint();
            EtudiantUnite eu= new EtudiantUnite ();
                call.add(eu.getContentPane());
                 home_pane.setVisible(false);
        
    }//GEN-LAST:event_codeunite_paneMouseClicked

    private void unite_paneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unite_paneMouseClicked
        // TODO add your handling code here:
        call.removeAll();
           call.repaint();
           Unite U= new Unite ();
                call.add(U.getContentPane());
                 home_pane.setVisible(false);
    }//GEN-LAST:event_unite_paneMouseClicked

    private void req4_paneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_req4_paneMousePressed
        // TODO add your handling code here:
        setColor(req4_pane);
        resetColor(enseignant_pane);
        resetColor(home_pane);
        resetColor(codeunite_pane);
        resetColor(unite_pane);
        resetColor(req1_pane);
        resetColor(req2_pane);
        resetColor(etudiant_pane);
        resetColor(req3_pane);
         home_pane.setVisible(false);
    }//GEN-LAST:event_req4_paneMousePressed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void req1_paneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_req1_paneMouseClicked
        // TODO add your handling code here:
          call.removeAll();
           call.repaint();
           NoteEgale NE= new NoteEgale ();
                call.add(NE.getContentPane());
                 home_pane.setVisible(false);
    }//GEN-LAST:event_req1_paneMouseClicked

    private void req2_paneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_req2_paneMouseClicked
        // TODO add your handling code here:
             call.removeAll();
           call.repaint();
           Moyenne moy= new Moyenne ();
                call.add(moy.getContentPane());
                 home_pane.setVisible(false);
    }//GEN-LAST:event_req2_paneMouseClicked

    private void req3_paneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_req3_paneMouseClicked
        // TODO add your handling code here:
         home_pane.setVisible(false);
        call.removeAll();
           call.repaint();
           MoyGeneral moyG= new MoyGeneral ();
                call.add(moyG.getContentPane());
    }//GEN-LAST:event_req3_paneMouseClicked

    private void req4_paneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_req4_paneMouseClicked
        // TODO add your handling code here:
        call.removeAll();
           call.repaint();
           EtudiantList EL= new EtudiantList();
                call.add(EL.getContentPane());
    }//GEN-LAST:event_req4_paneMouseClicked

    private void home_paneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_paneMouseClicked
        // TODO add your handling code here:
           call.removeAll();
           call.repaint();
          
           
           WelcomePage wp= new WelcomePage();
                call.add(wp.getContentPane());
    }//GEN-LAST:event_home_paneMouseClicked

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        // TODO add your handling code here:
        call.removeAll();
           call.repaint();
           Etudiant etu= new Etudiant();
                call.add(etu.getContentPane());
                 setColor(etudiant_pane);
                  home_pane.setVisible(false);
        resetColor(enseignant_pane);
        resetColor(home_pane);
        resetColor(codeunite_pane);
        resetColor(unite_pane);
        resetColor(req1_pane);
        resetColor(req2_pane);
        resetColor(req4_pane);
        resetColor(req3_pane);
    }//GEN-LAST:event_startMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        LoginPage p = new LoginPage();
        int response = JOptionPane.showConfirmDialog(this, "You Are About To Change The User , Do you wish to continue ?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            p.setVisible(true);
        this.setVisible(false);
        }
        
    }//GEN-LAST:event_jPanel2MouseClicked
public void setColor(JPanel panel){
	     panel.setBackground(new Color(85,65,118));
	}
	 public void resetColor(JPanel panel){
	panel.setBackground(new Color(64,43,100));
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel call;
    private javax.swing.JPanel codeunite_pane;
    private javax.swing.JPanel enseignant_pane;
    private javax.swing.JPanel etudiant_pane;
    private javax.swing.JPanel home_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel req1_pane;
    private javax.swing.JPanel req2_pane;
    private javax.swing.JPanel req3_pane;
    private javax.swing.JPanel req4_pane;
    private javax.swing.JLabel req4_paneee;
    private javax.swing.JLabel req4_paneee2;
    private javax.swing.JPanel sidepane;
    private javax.swing.JLabel start;
    private javax.swing.JPanel unite_pane;
    // End of variables declaration//GEN-END:variables
}
