/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseprojet;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author El Mysto
 */
public class Unite extends javax.swing.JFrame {
    Connection cn = JavaConnectDb.ConnecrDb();

    /**
     * Creates new form Unite
     */
    public Unite() {
        initComponents();
        inser_button.setEnabled(false);
        change_button.setEnabled(false);
        supp_button.setEnabled(false);
        change_pane.setVisible(false);
        inser_pane.setVisible(false);
        supp_pane.setVisible(false);
        mat_pane.setVisible(false);
        code_pane.setVisible(false);
        lib_pane.setVisible(false);
        nbh_pane.setVisible(false);
        
  
      
        refresh();
    }
    public void refresh(){
             try{
            Connection cn = JavaConnectDb.ConnecrDb();
           //   Statement myStmt2 = cn.createStatement();
             //  myStmt2.executeQuery("Alter Session set NLS_DATE_FORMAT = 'DD/MM/YYYY'");
            PreparedStatement ps=cn.prepareStatement("select * from unite");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)table1.getModel();
            tm.setRowCount(0);
            while(rs.next()){
            Object o[]={rs.getString("code_unite"),rs.getString("libelle"),rs.getInt("nbr_heures"),rs.getString("matricule_ens")};
            tm.addRow(o);
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        supp_pane = new javax.swing.JPanel();
        supp_button = new javax.swing.JButton();
        change_rad = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        supp_rad = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        code_pane = new javax.swing.JPanel();
        codeUNITE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inser_pane = new javax.swing.JPanel();
        inser_button = new javax.swing.JButton();
        change_pane = new javax.swing.JPanel();
        change_button = new javax.swing.JButton();
        mat_pane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricule = new javax.swing.JTextField();
        lib_pane = new javax.swing.JPanel();
        lib = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nbh_pane = new javax.swing.JPanel();
        nbh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        supp_button.setText("Supprimer ❌");
        supp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_buttonActionPerformed(evt);
            }
        });
        supp_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supp_buttonKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout supp_paneLayout = new javax.swing.GroupLayout(supp_pane);
        supp_pane.setLayout(supp_paneLayout);
        supp_paneLayout.setHorizontalGroup(
            supp_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supp_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supp_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        supp_paneLayout.setVerticalGroup(
            supp_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supp_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supp_button)
                .addContainerGap())
        );

        buttonGroup1.add(change_rad);
        change_rad.setText("Changement");
        change_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_radActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Insertion");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(supp_rad);
        supp_rad.setText("Suppression");
        supp_rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_radActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        table1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code Unite", "Libelle", "NB Heures", "Matricule Ens"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table1);

        codeUNITE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeUNITEActionPerformed(evt);
            }
        });
        codeUNITE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeUNITEKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codeUNITEKeyTyped(evt);
            }
        });

        jLabel2.setText("Code Unite");

        javax.swing.GroupLayout code_paneLayout = new javax.swing.GroupLayout(code_pane);
        code_pane.setLayout(code_paneLayout);
        code_paneLayout.setHorizontalGroup(
            code_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(code_paneLayout.createSequentialGroup()
                .addGroup(code_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(code_paneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(codeUNITE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(code_paneLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        code_paneLayout.setVerticalGroup(
            code_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(code_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codeUNITE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inser_button.setText("insert ↑");
        inser_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inser_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inser_paneLayout = new javax.swing.GroupLayout(inser_pane);
        inser_pane.setLayout(inser_paneLayout);
        inser_paneLayout.setHorizontalGroup(
            inser_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inser_paneLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(inser_button)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        inser_paneLayout.setVerticalGroup(
            inser_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inser_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inser_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        change_pane.setPreferredSize(new java.awt.Dimension(89, 45));

        change_button.setText("Changer");
        change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout change_paneLayout = new javax.swing.GroupLayout(change_pane);
        change_pane.setLayout(change_paneLayout);
        change_paneLayout.setHorizontalGroup(
            change_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, change_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(change_button)
                .addContainerGap())
        );
        change_paneLayout.setVerticalGroup(
            change_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(change_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(change_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Matricule");

        matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculeActionPerformed(evt);
            }
        });
        matricule.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matriculeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                matriculeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                matriculeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout mat_paneLayout = new javax.swing.GroupLayout(mat_pane);
        mat_pane.setLayout(mat_paneLayout);
        mat_paneLayout.setHorizontalGroup(
            mat_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mat_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mat_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mat_paneLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)))
                .addContainerGap())
        );
        mat_paneLayout.setVerticalGroup(
            mat_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mat_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lib_pane.setPreferredSize(new java.awt.Dimension(140, 62));

        lib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libActionPerformed(evt);
            }
        });
        lib.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                libKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                libKeyTyped(evt);
            }
        });

        jLabel4.setText("Libelle");

        javax.swing.GroupLayout lib_paneLayout = new javax.swing.GroupLayout(lib_pane);
        lib_pane.setLayout(lib_paneLayout);
        lib_paneLayout.setHorizontalGroup(
            lib_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lib_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lib, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lib_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(54, 54, 54))
        );
        lib_paneLayout.setVerticalGroup(
            lib_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lib_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbhActionPerformed(evt);
            }
        });
        nbh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nbhKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nbhKeyTyped(evt);
            }
        });

        jLabel5.setText("NB Heures");

        javax.swing.GroupLayout nbh_paneLayout = new javax.swing.GroupLayout(nbh_pane);
        nbh_pane.setLayout(nbh_paneLayout);
        nbh_paneLayout.setHorizontalGroup(
            nbh_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nbh_paneLayout.createSequentialGroup()
                .addGroup(nbh_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nbh_paneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nbh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nbh_paneLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nbh_paneLayout.setVerticalGroup(
            nbh_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nbh_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nbh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton1)
                        .addGap(48, 48, 48)
                        .addComponent(supp_rad)
                        .addGap(48, 48, 48)
                        .addComponent(change_rad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(code_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lib_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nbh_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mat_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(supp_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(change_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(inser_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supp_rad)
                    .addComponent(jRadioButton1)
                    .addComponent(change_rad))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(code_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mat_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbh_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lib_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supp_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inser_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = JavaConnectDb.ConnecrDb();
            String sql ="delete from unite where code_unite = ?";
            PreparedStatement ps=cn.prepareStatement(sql);
            
            ps.setString(1,codeUNITE.getText());
            
            ps.executeUpdate();
            refresh();
            JOptionPane.showMessageDialog(this,"supprimé avec sucess");

            
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
    }//GEN-LAST:event_supp_buttonActionPerformed

    private void supp_buttonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supp_buttonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_supp_buttonKeyReleased

    private void change_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_radActionPerformed
        // TODO add your handling code here:
        lib.setBackground(new Color(255,255,255)); 
        nbh.setEditable(true); nbh.setBackground(new Color(255,255,255)); 
        matricule.setBackground(new Color(255,255,255));
        change_button.setEnabled(false);
        
        codeUNITE.setText("");

        mat_pane.setVisible(false);
        nbh_pane.setVisible(false);
        lib_pane.setVisible(false);
        change_pane.setVisible(true);
        code_pane.setVisible(true);
        
        supp_pane.setVisible(false);
        inser_pane.setVisible(false);
        codeUNITE.setText("");
        lib.setText("");
        nbh.setText("");
        matricule.setText("");
    }//GEN-LAST:event_change_radActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        lib.setBackground(new Color(255,255,255)); 
        nbh.setEditable(true); nbh.setBackground(new Color(255,255,255)); 
        matricule.setBackground(new Color(255,255,255));
        mat_pane.setVisible(true);
        change_pane.setVisible(false);
        code_pane.setVisible(true);
        nbh_pane.setVisible(true);
        lib_pane.setVisible(true);
        supp_pane.setVisible(false);
        inser_pane.setVisible(true);
        inser_button.setEnabled(false);
        codeUNITE.setText("");
        lib.setText("");
        nbh.setText("");
        matricule.setText("");
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void supp_radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_radActionPerformed
        // TODO add your handling code here:
        supp_button.setEnabled(false);
       mat_pane.setVisible(false);
        nbh_pane.setVisible(false);
        lib_pane.setVisible(false);
        change_pane.setVisible(false);
        code_pane.setVisible(true);
        
        supp_pane.setVisible(true);
        inser_pane.setVisible(false);
        codeUNITE.setText("");
        lib.setText("");
        nbh.setText("");
        matricule.setText("");
    }//GEN-LAST:event_supp_radActionPerformed

    private void codeUNITEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeUNITEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeUNITEActionPerformed

    private void codeUNITEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeUNITEKeyReleased
        // TODO add your handling code here:
        if((lib.getText().equals(""))||(codeUNITE.getText().equals(""))||(matricule.getText().equals(""))||(nbh.getText().equals(""))){
            inser_button.setEnabled(false);
        }
        else {
            inser_button.setEnabled(true);
        }

        /**************** change button ******//////////////
      /*  try{

            Connection cn = JavaConnectDb.ConnecrDb();
            Statement myStmt3 = cn.createStatement();
            if(matricule.getText().equals("")){

            }else{
                PreparedStatement st = cn.prepareStatement("SELECT *  FROM etudiantunite WHERE code_unite = ? and matricule_etu=?");
                st.setString(1,codeUNITE.getText());
                st.setString(2,matricule.getText());
                ResultSet myRs1 = st.executeQuery();
                if(myRs1.next()){
                    noteCC.setText(myRs1.getString("note_cc"));
                    noteTP.setText(myRs1.getString("note_tp"));
                    noteEX.setText(myRs1.getString("note_examen"));
                    change_button.setEnabled(true);
                    modulename_pane.setVisible(false);
                }else{
                    noteCC.setText("");
                    noteTP.setText("");
                    noteEX.setText("");
                    change_button.setEnabled(false);
                }

            }

        }
        catch (Exception e){

        }*/
      /******* FILL WHEN CODE IS fOUND */////
      try{
            Connection cn = JavaConnectDb.ConnecrDb();
            PreparedStatement st = cn.prepareStatement("SELECT *  FROM unite WHERE code_unite = ? ");
           st.setString(1,codeUNITE.getText());
            ResultSet myRs3 = st.executeQuery();
            if(myRs3.next()) {
                lib.setText(myRs3.getString("libelle"));
                matricule.setText(myRs3.getString("matricule_ens"));
                nbh.setText(myRs3.getString("nbr_heures"));
                supp_button.setEnabled(true);
                inser_button.setEnabled(true);
            }else{
                supp_button.setEnabled(false);
                inser_button.setEnabled(false);
                lib.setText("");
                matricule.setText("");
                nbh.setText("");
            }

        }catch(Exception e){
         
        }
      /************** on the delete *////////////////
      try{  
          if(supp_rad.isSelected()){
             
               Connection cn = JavaConnectDb.ConnecrDb();
            PreparedStatement st = cn.prepareStatement("SELECT *  FROM unite WHERE code_unite = ? ");
           st.setString(1,codeUNITE.getText());
            ResultSet myRs3 = st.executeQuery();
            if(myRs3.next()) {
                lib_pane.setVisible(true); lib.setEditable(false); lib.setBackground(new Color(204,204,255)); 
                nbh_pane.setVisible(true); matricule.setEditable(false); matricule.setBackground(new Color(204,204,255)); 
                mat_pane.setVisible(true);  nbh.setEditable(false); nbh.setBackground(new Color(204,204,255)); 
                
                lib.setText(myRs3.getString("libelle"));
                matricule.setText(myRs3.getString("matricule_ens"));
                nbh.setText(myRs3.getString("nbr_heures"));
                supp_button.setEnabled(true);
                inser_button.setEnabled(true);
            }else{
                lib_pane.setVisible(false);  lib.setEditable(true); lib.setBackground(new Color(255,255,255)); 
                nbh_pane.setVisible(false);  nbh.setEditable(true); nbh.setBackground(new Color(255,255,255)); 
                mat_pane.setVisible(false);  matricule.setEditable(true); matricule.setBackground(new Color(255,255,255)); 
                supp_button.setEnabled(false);
                inser_button.setEnabled(false);
                lib.setText("");
                matricule.setText("");
                nbh.setText("");
            }
              
          }

        }catch(Exception e){
         
        }
       /******************** ON THE CHANGE RADBUTTON ******************/
       try{  
          if(change_rad.isSelected()){
               Connection cn = JavaConnectDb.ConnecrDb();
            PreparedStatement st = cn.prepareStatement("SELECT *  FROM unite WHERE code_unite = ? ");
           st.setString(1,codeUNITE.getText());
            ResultSet myRs3 = st.executeQuery();
            if(myRs3.next()) {
                lib_pane.setVisible(true);  
                nbh_pane.setVisible(true); 
                mat_pane.setVisible(true); 
                
                lib.setText(myRs3.getString("libelle"));
                matricule.setText(myRs3.getString("matricule_ens"));
                nbh.setText(myRs3.getString("nbr_heures"));
                change_button.setEnabled(true);
            }else{
                lib_pane.setVisible(false);  
                nbh_pane.setVisible(false); 
                mat_pane.setVisible(false);  
                change_button.setEnabled(false);
                lib.setText("");
                matricule.setText("");
                nbh.setText("");
            }
              
          }

        }catch(Exception e){
         
        }

    }//GEN-LAST:event_codeUNITEKeyReleased

    private void codeUNITEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeUNITEKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_codeUNITEKeyTyped

    private void inser_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inser_buttonActionPerformed
        // TODO add your handling code here:
        try {
            
            String sql ="insert into unite(code_unite,libelle,nbr_heures,matricule_ens) values (?,?,?,?)";
            PreparedStatement ps=cn.prepareStatement(sql);
            ps.setInt(4,Integer.parseInt(matricule.getText()));
            ps.setString(1,codeUNITE.getText());
            ps.setString(2,lib.getText());
            ps.setString(3,nbh.getText());
            ps.executeUpdate();
            refresh();
            JOptionPane.showMessageDialog(this,"saved sucessfully");
            codeUNITE.setText("");
            nbh.setText("");
            lib.setText("");
            matricule.setText("");

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_inser_buttonActionPerformed

    private void change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = JavaConnectDb.ConnecrDb();

            PreparedStatement st = cn.prepareStatement("UPDATE unite Set libelle = ? , nbr_heures = ? , matricule_ens = ? where code_unite = ?");
            st.setString(1,lib.getText());
            st.setInt(2,Integer.parseInt(nbh.getText()));
            st.setInt(3,Integer.parseInt(matricule.getText()));
            st.setString(4,codeUNITE.getText());
            st.executeUpdate();
            refresh();
            
            lib.setText("");
            nbh.setText("");
            matricule.setText("");
            
            JOptionPane.showMessageDialog(this,"changé avec succès");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }

    }//GEN-LAST:event_change_buttonActionPerformed

    private void matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculeActionPerformed

    private void matriculeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculeKeyPressed

    private void matriculeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculeKeyReleased
        // TODO add your handling code here:
        if((lib.getText().equals(""))||(codeUNITE.getText().equals(""))||(matricule.getText().equals(""))||(nbh.getText().equals(""))){
            inser_button.setEnabled(false);
        }
        else {
            inser_button.setEnabled(true);}
        /*try{
            Connection cn = JavaConnectDb.ConnecrDb();
            Statement myStmt3 = cn.createStatement();
            ResultSet myRs3 = myStmt3.executeQuery("select * from enseignant where matricule_ens = "+matricule.getText());
            if(myRs3.next()) {
                nom.setText(myRs3.getString("nom_ens"));
                supp_button.setEnabled(true);
            }else{
                supp_button.setEnabled(false);
                nom.setText("");
            }

        }catch(Exception e){

        }*/
    }//GEN-LAST:event_matriculeKeyReleased

    private void matriculeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculeKeyTyped

    private void libActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libActionPerformed

    private void libKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_libKeyReleased
        // TODO add your handling code here:
        if((lib.getText().equals(""))||(codeUNITE.getText().equals(""))||(matricule.getText().equals(""))||(nbh.getText().equals(""))){
            inser_button.setEnabled(false);
        }
        else {
            inser_button.setEnabled(true);}
        
    }//GEN-LAST:event_libKeyReleased

    private void libKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_libKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_libKeyTyped

    private void nbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbhActionPerformed

    private void nbhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nbhKeyReleased
        // TODO add your handling code here:
        if((lib.getText().equals(""))||(codeUNITE.getText().equals(""))||(matricule.getText().equals(""))||(nbh.getText().equals(""))){
            inser_button.setEnabled(false);
        }
        else {
            inser_button.setEnabled(true);}
    }//GEN-LAST:event_nbhKeyReleased

    private void nbhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nbhKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nbhKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Unite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Unite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Unite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Unite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Unite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton change_button;
    private javax.swing.JPanel change_pane;
    private javax.swing.JRadioButton change_rad;
    private javax.swing.JTextField codeUNITE;
    private javax.swing.JPanel code_pane;
    private javax.swing.JButton inser_button;
    private javax.swing.JPanel inser_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lib;
    private javax.swing.JPanel lib_pane;
    private javax.swing.JPanel mat_pane;
    private javax.swing.JTextField matricule;
    private javax.swing.JTextField nbh;
    private javax.swing.JPanel nbh_pane;
    private javax.swing.JButton supp_button;
    private javax.swing.JPanel supp_pane;
    private javax.swing.JRadioButton supp_rad;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
